# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='应用程序名称')),
                ('net_version', models.SmallIntegerField(choices=[(1, 'v1.1'), (2, 'v2.0'), (3, 'v3.5'), (4, 'v4.0'), (5, 'v4.5')], default=2, verbose_name='framwork版本')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='域名')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='应用程序名称')),
                ('webpath', models.CharField(max_length=64, verbose_name='物理路径')),
                ('app_pool', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Leonardo.AppPool', verbose_name='应用程序名称')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='网站名称')),
                ('webpath', models.CharField(max_length=64, unique=True, verbose_name='物理路径')),
                ('public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('app_pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Leonardo.AppPool', verbose_name='应用程序池')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.AddField(
            model_name='virtualapp',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leonardo.WebSite', verbose_name='父站点'),
        ),
        migrations.AddField(
            model_name='virtualapp',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='domain',
            name='web_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leonardo.WebSite'),
        ),
    ]
