# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leonardo', '0002_auto_20160823_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='服务器')),
                ('ip_addr', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('host_type', models.SmallIntegerField(choices=[(1, 'web'), (2, 'SQL Server')], verbose_name='服务器类型')),
            ],
        ),
        migrations.AlterField(
            model_name='website',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='website',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Leonardo.Host', verbose_name='所属服务器'),
            preserve_default=False,
        ),
    ]
