# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leonardo', '0003_auto_20160824_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已使用'), (0, '空闲')], default=0, verbose_name='绑定状态'),
        ),
    ]
